import logging
import os
from pathlib import Path
from typing import Optional

import tkinter as tk
from tkinter import ttk, messagebox


LOG_DIR_NAME = "logs"
LOG_FILE_NAME = "onboarding.log"


class _EnvConfig:
    """Minimal .env reader/writer focused on a small key set."""

    def __init__(self, base_dir: Path):
        self.base_dir = base_dir
        self.env_path = base_dir / ".env"
        self.example_path = base_dir / ".env.example"
        self._values: dict[str, str] = {}

    def load(self) -> None:
        if self.env_path.exists():
            self._values = self._parse_file(self.env_path)
        elif self.example_path.exists():
            # Start from example defaults
            self._values = self._parse_file(self.example_path)
        else:
            self._values = {}

    @staticmethod
    def _parse_file(path: Path) -> dict[str, str]:
        values: dict[str, str] = {}
        for line in path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, val = line.split("=", 1)
            values[key.strip()] = val.strip()
        return values

    def get(self, key: str, default: str = "") -> str:
        return self._values.get(key, default)

    def set(self, key: str, value: str) -> None:
        self._values[key] = value

    def save(self) -> None:
        """Rewrite .env with our known values, preserving only simple comments."""
        lines: list[str] = [
            "# Auto-generated by Temporal Bot onboarding wizard",
            "# Edit with care or re-run the GUI onboarding if keys change.",
            "",
        ]
        for key, value in self._values.items():
            lines.append(f"{key}={value}")
        self.env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _init_logger(base_dir: Path) -> logging.Logger:
    log_dir = base_dir / LOG_DIR_NAME
    log_dir.mkdir(exist_ok=True)
    log_path = log_dir / LOG_FILE_NAME
    logger = logging.getLogger("temporal_bot.onboarding")
    if not logger.handlers:
        handler = logging.FileHandler(log_path, encoding="utf-8")
        handler.setFormatter(
            logging.Formatter(
                "%(asctime)s | %(levelname)s | %(message)s",
                datefmt="%Y-%m-%d %H:%M:%S",
            )
        )
        logger.addHandler(handler)
        logger.setLevel(logging.INFO)
    return logger


class CredentialsDialog(tk.Toplevel):
    """Modal dialog that collects Binance + Telegram credentials."""

    def __init__(self, parent: tk.Tk, initial: dict[str, str]):
        super().__init__(parent)
        self.title("Temporal Bot — First-time Setup")
        self.resizable(False, False)
        self.configure(bg="#0d0f14")
        self.transient(parent)
        self.grab_set()

        self._result: Optional[dict[str, str]] = None

        self._build_widgets(initial)
        self.protocol("WM_DELETE_WINDOW", self._on_cancel)

        self.update_idletasks()
        self.geometry(
            f"+{parent.winfo_rootx() + 80}+{parent.winfo_rooty() + 80}"
        )

    # --------------------------------------------------------------------- widgets
    def _build_widgets(self, initial: dict[str, str]) -> None:
        fg = "#b0b8c8"
        bg = "#0d0f14"
        accent = "#ffd54f"

        frame = tk.Frame(self, bg=bg, padx=16, pady=16)
        frame.pack(fill="both", expand=True)

        title = tk.Label(
            frame,
            text="API Configuration (one-time)",
            bg=bg,
            fg=accent,
            font=("Courier New", 12, "bold"),
        )
        title.grid(row=0, column=0, columnspan=2, sticky="w", pady=(0, 8))

        subtitle = tk.Label(
            frame,
            text=(
                "Enter your Binance API keys (read-only) and, optionally,\n"
                "a Telegram bot token. Values are stored in the local .env file."
            ),
            bg=bg,
            fg=fg,
            justify="left",
            font=("Courier New", 9),
        )
        subtitle.grid(row=1, column=0, columnspan=2, sticky="w", pady=(0, 12))

        # Binance
        tk.Label(
            frame,
            text="Binance API Key *",
            bg=bg,
            fg=fg,
            anchor="w",
        ).grid(row=2, column=0, sticky="w")

        self.var_binance_key = tk.StringVar(
            value=initial.get("BINANCE_API_KEY", "")
        )
        tk.Entry(
            frame,
            textvariable=self.var_binance_key,
            show="*",
            width=40,
        ).grid(row=2, column=1, sticky="w", pady=2)

        tk.Label(
            frame,
            text="Binance API Secret *",
            bg=bg,
            fg=fg,
            anchor="w",
        ).grid(row=3, column=0, sticky="w", pady=(6, 0))

        self.var_binance_secret = tk.StringVar(
            value=initial.get("BINANCE_API_SECRET", "")
        )
        tk.Entry(
            frame,
            textvariable=self.var_binance_secret,
            show="*",
            width=40,
        ).grid(row=3, column=1, sticky="w", pady=2)

        # Telegram (optional)
        tk.Label(
            frame,
            text="Telegram Bot Token (optional)",
            bg=bg,
            fg=fg,
            anchor="w",
        ).grid(row=4, column=0, sticky="w", pady=(10, 0))

        self.var_telegram = tk.StringVar(
            value=initial.get("TELEGRAM_BOT_TOKEN", "")
        )
        tk.Entry(
            frame,
            textvariable=self.var_telegram,
            show="*",
            width=40,
        ).grid(row=4, column=1, sticky="w", pady=2)

        # Buttons
        btn_frame = tk.Frame(frame, bg=bg)
        btn_frame.grid(row=5, column=0, columnspan=2, pady=(14, 0), sticky="e")

        cancel_btn = ttk.Button(btn_frame, text="Cancel", command=self._on_cancel)
        cancel_btn.pack(side="right", padx=(0, 8))

        save_btn = ttk.Button(btn_frame, text="Save & Continue", command=self._on_save)
        save_btn.pack(side="right")

    # --------------------------------------------------------------------- actions
    def _on_save(self) -> None:
        key = self.var_binance_key.get().strip()
        secret = self.var_binance_secret.get().strip()
        telegram = self.var_telegram.get().strip()

        if not key or not secret:
            messagebox.showerror(
                "Missing credentials",
                "Binance API Key and Secret are required.",
                parent=self,
            )
            return

        self._result = {
            "BINANCE_API_KEY": key,
            "BINANCE_API_SECRET": secret,
            "TELEGRAM_BOT_TOKEN": telegram,
        }
        self.destroy()

    def _on_cancel(self) -> None:
        if messagebox.askyesno(
            "Exit",
            "Credentials are required to fetch data.\n\nExit the application?",
            parent=self,
        ):
            self._result = None
            self.destroy()

    # --------------------------------------------------------------------- public
    def run(self) -> Optional[dict[str, str]]:
        self.wait_window()
        return self._result


def ensure_credentials(base_dir: Path, parent: tk.Tk) -> bool:
    """
    Ensure required credentials exist in .env.

    Returns True if credentials are present (existing or newly saved),
    False if the user cancelled and the app should exit.
    """
    logger = _init_logger(base_dir)
    env = _EnvConfig(base_dir)
    env.load()

    current_key = env.get("BINANCE_API_KEY", "")
    current_secret = env.get("BINANCE_API_SECRET", "")
    current_telegram = env.get("TELEGRAM_BOT_TOKEN", "")

    needs_onboarding = (
        not current_key
        or current_key == "your_binance_api_key_here"
        or not current_secret
        or current_secret == "your_binance_api_secret_here"
    )

    if not needs_onboarding:
        logger.info("Credentials already configured — skipping onboarding dialog.")
        return True

    initial = {
        "BINANCE_API_KEY": current_key,
        "BINANCE_API_SECRET": current_secret,
        "TELEGRAM_BOT_TOKEN": current_telegram,
    }

    logger.info("Launching onboarding dialog — credentials not configured.")
    dialog = CredentialsDialog(parent=parent, initial=initial)
    result = dialog.run()

    if result is None:
        logger.warning("User cancelled onboarding dialog — exiting GUI.")
        return False

    env.set("BINANCE_API_KEY", result["BINANCE_API_KEY"])
    env.set("BINANCE_API_SECRET", result["BINANCE_API_SECRET"])
    # Telegram is optional; only store when provided
    if result["TELEGRAM_BOT_TOKEN"]:
        env.set("TELEGRAM_BOT_TOKEN", result["TELEGRAM_BOT_TOKEN"])

    env.save()

    # Also update in-memory environment and config module so running code
    # sees the new values without requiring a restart.
    os.environ["BINANCE_API_KEY"] = result["BINANCE_API_KEY"]
    os.environ["BINANCE_API_SECRET"] = result["BINANCE_API_SECRET"]
    if result["TELEGRAM_BOT_TOKEN"]:
        os.environ["TELEGRAM_BOT_TOKEN"] = result["TELEGRAM_BOT_TOKEN"]

    try:
        import config as app_config

        app_config.BINANCE_API_KEY = result["BINANCE_API_KEY"]
        app_config.BINANCE_API_SECRET = result["BINANCE_API_SECRET"]
        if result["TELEGRAM_BOT_TOKEN"]:
            app_config.TELEGRAM_BOT_TOKEN = result["TELEGRAM_BOT_TOKEN"]
    except Exception:
        # If config import fails for some reason, we still have .env and os.environ updated.
        pass

    logger.info(
        "Credentials saved to .env (Binance keys + %s).",
        "Telegram token" if result["TELEGRAM_BOT_TOKEN"] else "no Telegram token",
    )

    messagebox.showinfo(
        "Setup complete",
        "API credentials saved.\nYou can change them later by editing the .env file.",
        parent=parent,
    )

    return True

